spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5436/ps_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
    pool:
      metrics-enabled: true
      log-leaked-sessions: true
      max-connection-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    prefer-ip-address: true

whitelisted-paths: /swagger-ui/**, /v3/api-docs/**, /v3/api-docs.yaml, /swagger-ui.html, /bus/**, /actuator/**
orders-cron-active: true
STRIPE_SECRET_KEY= sk_test_placeholder
notification-token: cHJvZHVjdC1zZXJ2aWNlLXRva2Vu